name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  Release:
    runs-on: [self-hosted]
    env:
        PROJECT_PATH: ".\\"
        BUILD_METHOD_WIN64: "BuildProject.BuildWindows64"
        gameName: "Oblivion"
        projectVersion: 
        output:
        input:
    steps:
      - uses: actions/checkout@v2  
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
            strip_v: false
      - name: Build For Windows 64 bits
        run: |
          $env:projectVersion = "${{steps.tag.outputs.tag}}"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN64 -quit"
      - name: Create_Setup 
        id: create_setup
        run: |
          $env:output = "$env:PROJECT_PATH\Setup.exe"
          $env:input = "$env:PROJECT_PATH\Builds\${{ steps.tag.outputs.tagname }}\"
          cd $input
          Start-Process -Wait 'C:\Program Files\7-Zip\7z.exe' -ArgumentList "a -sfx7z.sfx $env:output $env:input"
          echo echo "::set-output name=setup::$env:output"
      - name: Create_Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.tag.outputs.tagname }}
          tag_name: ${{ github.ref }}
          body_path: Changelog.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.create_setup.outputs.setup }}
          asset_name: Setup.exe
          asset_content_type: application/exe
